package: codemagic-cli-tools
repo: https://github.com/codemagic-ci-cd/cli-tools
pypi_url: https://pypi.org/project/codemagic-cli-tools/
extension_type: pure
python_versions: []
install_method: pip
install_command: ''
test_command: ''
test_framework: pytest
uses_xdist: false
timeout: null
skip: false
skip_reason: null
skip_versions: {}
notes: ''
enriched: false
clone_depth: null
import_name: null
